
package com.wangjin.webservicedemo.temp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SP_TSM_WS", targetNamespace = "http://tsm.sp.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SPTSMWS {


    /**
     * 
     * @param customContactsSysReq
     * @return
     *     returns com.wangjin.webservicedemo.temp.CUSTOMCONTACTSSYSRESP
     */
    @WebMethod(operationName = "CUSTOM_CONTACTS_SYS")
    @WebResult(name = "CUSTOM_CONTACTS_SYSReturn", targetNamespace = "http://tsm.sp.com", partName = "CUSTOM_CONTACTS_SYSReturn")
    public CUSTOMCONTACTSSYSRESP customCONTACTSSYS(
        @WebParam(name = "custom_contacts_sys_req", targetNamespace = "http://tsm.sp.com", partName = "custom_contacts_sys_req")
        CUSTOMCONTACTSSYSREQ customContactsSysReq);

    /**
     * 
     * @param mwTransReq
     * @return
     *     returns com.wangjin.webservicedemo.temp.MWTRANSRESP
     */
    @WebMethod(operationName = "MW_TRANS")
    @WebResult(name = "MW_TRANSReturn", targetNamespace = "http://tsm.sp.com", partName = "MW_TRANSReturn")
    public MWTRANSRESP mwTRANS(
        @WebParam(name = "mw_trans_req", targetNamespace = "http://tsm.sp.com", partName = "mw_trans_req")
        MWTRANSREQ mwTransReq);

    /**
     * 
     * @param posPersoReq
     * @return
     *     returns com.wangjin.webservicedemo.temp.POSPERSORESP
     */
    @WebMethod(operationName = "POS_PERSO")
    @WebResult(name = "POS_PERSOReturn", targetNamespace = "http://tsm.sp.com", partName = "POS_PERSOReturn")
    public POSPERSORESP posPERSO(
        @WebParam(name = "pos_perso_req", targetNamespace = "http://tsm.sp.com", partName = "pos_perso_req")
        POSPERSOREQ posPersoReq);

    /**
     * 
     * @param synAppReq
     * @return
     *     returns com.wangjin.webservicedemo.temp.SYNAPPRESP
     */
    @WebMethod(operationName = "SYN_APP")
    @WebResult(name = "SYN_APPReturn", targetNamespace = "http://tsm.sp.com", partName = "SYN_APPReturn")
    public SYNAPPRESP synAPP(
        @WebParam(name = "syn_app_req", targetNamespace = "http://tsm.sp.com", partName = "syn_app_req")
        SYNAPPREQ synAppReq);

    /**
     * 
     * @param synMackeyReq
     * @return
     *     returns com.wangjin.webservicedemo.temp.SYNMACKEYRESP
     */
    @WebMethod(operationName = "SYN_MACKEY")
    @WebResult(name = "SYN_MACKEYReturn", targetNamespace = "http://tsm.sp.com", partName = "SYN_MACKEYReturn")
    public SYNMACKEYRESP synMACKEY(
        @WebParam(name = "syn_mackey_req", targetNamespace = "http://tsm.sp.com", partName = "syn_mackey_req")
        SYNMACKEYREQ synMackeyReq);

    /**
     * 
     * @param synAppmacReq
     * @return
     *     returns com.wangjin.webservicedemo.temp.SYNAPPMACRESP
     */
    @WebMethod(operationName = "SYN_APPMAC")
    @WebResult(name = "SYN_APPMACReturn", targetNamespace = "http://tsm.sp.com", partName = "SYN_APPMACReturn")
    public SYNAPPMACRESP synAPPMAC(
        @WebParam(name = "syn_appmac_req", targetNamespace = "http://tsm.sp.com", partName = "syn_appmac_req")
        SYNAPPMACREQ synAppmacReq);

    /**
     * 
     * @param userAucReq
     * @return
     *     returns com.wangjin.webservicedemo.temp.USERAUCRESP
     */
    @WebMethod(operationName = "USER_AUC")
    @WebResult(name = "USER_AUCReturn", targetNamespace = "http://tsm.sp.com", partName = "USER_AUCReturn")
    public USERAUCRESP userAUC(
        @WebParam(name = "user_auc_req", targetNamespace = "http://tsm.sp.com", partName = "user_auc_req")
        USERAUCREQ userAucReq);

    /**
     * 
     */
    @WebMethod(operationName = "BIZ_DATA_SYNC")
    public void bizDATASYNC();

    /**
     * 
     * @param userEventReq
     * @return
     *     returns com.wangjin.webservicedemo.temp.USEREVENTRESP
     */
    @WebMethod(operationName = "USER_EVENT")
    @WebResult(name = "USER_EVENTReturn", targetNamespace = "http://tsm.sp.com", partName = "USER_EVENTReturn")
    public USEREVENTRESP userEVENT(
        @WebParam(name = "user_event_req", targetNamespace = "http://tsm.sp.com", partName = "user_event_req")
        USEREVENTREQ userEventReq);

}
